import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Theme } from "@radix-ui/themes";
import "@radix-ui/themes/styles.css";
import "./../globals.css";

import MobileNav from "@/app/components/MobileNav";
import DesktopNav from "../components/DesktopNav";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "VIBE",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-gray-50 dark:bg-gray-900`}
      >
        <Theme>
          <DesktopNav />
          <MobileNav />

          <div className="md:pl-48">
            <main className="min-h-screen p-4 pb-28 md:pb-4">{children}</main>
          </div>
        </Theme>
      </body>
    </html>
  );
}
