"use client";

import { useActionState, useState } from "react";
import { BarChart3, Plus, Trash2 } from "lucide-react";
import { createPoll, deletePoll, togglePollLive } from "@/actions";

type Poll = {
  id: string; question: string; isActive: boolean; createdAt: string; startsAt: string | null; expiresAt: string | null;
  options: { id: string; label: string; votes: { id: string; profile: { name: string | null; username: string | null; avatar: string | null } }[] }[];
};

export default function AdminPollManager({ polls, de, referenceTime }: { polls: Poll[]; de: boolean; referenceTime: string }) {
  const [options, setOptions] = useState(["", ""]);
  const [draftState, draftAction, draftPending] = useActionState(createPoll, {});
  const format = new Intl.DateTimeFormat(de ? "de-DE" : "en-US", { dateStyle: "medium", timeStyle: "short" });
  return <section className="space-y-6">
    <div className="flex items-center gap-3"><span className="grid size-10 place-items-center rounded-2xl bg-orange-500/15 text-orange-500"><BarChart3 size={20} /></span><div><h2 className="font-black text-slate-900 dark:text-white">{de ? "Homepage-Polls" : "Homepage polls"}</h2><p className="text-sm text-slate-500 dark:text-slate-400">{de ? "Entwürfe vorbereiten und für 72 Stunden live schalten." : "Prepare drafts and put one live for 72 hours."}</p></div></div>
    <form action={draftAction} className="rounded-2xl border border-slate-200 bg-slate-50 p-4 dark:border-slate-700 dark:bg-slate-800/50">
      <label className="block text-sm font-bold text-slate-800 dark:text-white">{de ? "Neue Frage" : "New question"}<input required name="question" maxLength={240} placeholder={de ? "Was möchtest du die Community fragen?" : "What would you like to ask the community?"} className="mt-2 w-full rounded-xl border border-slate-300 bg-white px-3 py-2.5 text-sm outline-none focus:border-orange-500 dark:border-slate-600 dark:bg-slate-900" /></label>
      <div className="mt-3 space-y-2">{options.map((_, index) => <div key={index} className="flex gap-2"><input required name="option" maxLength={120} placeholder={`${de ? "Antwort" : "Answer"} ${index + 1}`} className="min-w-0 flex-1 rounded-xl border border-slate-300 bg-white px-3 py-2.5 text-sm outline-none focus:border-orange-500 dark:border-slate-600 dark:bg-slate-900" />{options.length > 2 && <button type="button" aria-label="Remove answer" onClick={() => setOptions(options.filter((_, itemIndex) => itemIndex !== index))} className="rounded-xl border border-slate-300 px-3 text-slate-500 hover:text-rose-500 dark:border-slate-600"><Trash2 size={16}/></button>}</div>)}</div>
      {draftState.error ? <p role="alert" className="mt-3 rounded-xl border border-rose-300/60 bg-rose-50 px-3 py-2 text-sm font-semibold text-rose-700 dark:border-rose-500/30 dark:bg-rose-500/10 dark:text-rose-200">{draftState.error}</p> : null}
      {draftState.saved ? <p className="mt-3 rounded-xl border border-emerald-300/60 bg-emerald-50 px-3 py-2 text-sm font-semibold text-emerald-700 dark:border-emerald-500/30 dark:bg-emerald-500/10 dark:text-emerald-200">{de ? "Poll als Entwurf gespeichert." : "Poll saved as a draft."}</p> : null}
      <div className="mt-4 flex flex-wrap gap-2"><button type="button" disabled={options.length >= 6} onClick={() => setOptions([...options, ""])} className="inline-flex items-center gap-1 rounded-xl border border-slate-300 px-3 py-2 text-sm font-bold text-slate-700 disabled:opacity-40 dark:border-slate-600 dark:text-slate-200"><Plus size={16}/>{de ? "Antwort" : "Answer"}</button><button disabled={draftPending} className="rounded-xl bg-linear-to-r from-orange-500 to-rose-500 px-4 py-2 text-sm font-black text-white shadow disabled:opacity-60">{draftPending ? (de ? "Speichert …" : "Saving …") : (de ? "Als Entwurf speichern" : "Save draft")}</button></div>
    </form>
    <div className="space-y-3">{polls.length === 0 ? <p className="rounded-2xl border border-dashed border-slate-300 p-5 text-sm text-slate-500 dark:border-slate-700 dark:text-slate-400">{de ? "Noch keine Polls vorbereitet." : "No polls prepared yet."}</p> : polls.map((poll) => {
      const now = new Date(referenceTime).getTime(); const live = poll.isActive && Boolean(poll.expiresAt && new Date(poll.expiresAt).getTime() > now); const ended = Boolean(poll.expiresAt && new Date(poll.expiresAt).getTime() <= now); const total = poll.options.reduce((sum, option) => sum + option.votes.length, 0);
      return <article key={poll.id} className="rounded-2xl border border-slate-200 p-4 dark:border-slate-700"><div className="flex flex-wrap items-start justify-between gap-3"><div><div className="flex items-center gap-2"><span className={`rounded-full px-2 py-0.5 text-xs font-black ${live ? "bg-emerald-500/15 text-emerald-600 dark:text-emerald-300" : ended ? "bg-slate-200 text-slate-600 dark:bg-slate-800 dark:text-slate-300" : "bg-amber-500/15 text-amber-700 dark:text-amber-300"}`}>{live ? (de ? "LIVE" : "LIVE") : ended ? (de ? "ABGELAUFEN" : "ENDED") : (de ? "ENTWURF" : "DRAFT")}</span><span className="text-xs text-slate-500">{total} {de ? "Stimmen" : "votes"}</span></div><h3 className="mt-2 font-black text-slate-900 dark:text-white">{poll.question}</h3>{live && poll.expiresAt && <p className="mt-1 text-xs text-slate-500">{de ? "Läuft bis" : "Live until"} {format.format(new Date(poll.expiresAt))}</p>}</div><div className="flex gap-2"><form action={togglePollLive}><input type="hidden" name="pollId" value={poll.id}/><button className={`rounded-xl px-3 py-2 text-xs font-black text-white ${live ? "bg-slate-600" : "bg-emerald-600"}`}>{live ? (de ? "Offline nehmen" : "Take offline") : (de ? "72 Std. live" : "Go live for 72h")}</button></form><form action={deletePoll}><input type="hidden" name="pollId" value={poll.id}/><button aria-label="Delete poll" className="rounded-xl border border-rose-300 p-2 text-rose-500"><Trash2 size={16}/></button></form></div></div>
      <div className="mt-4 space-y-2">{poll.options.map((option) => { const votes = option.votes.length; const percent = total ? Math.round(votes / total * 100) : 0; return <div key={option.id}><div className="flex justify-between gap-3 text-sm"><span className="font-semibold text-slate-800 dark:text-slate-200">{option.label}</span><span className="text-slate-500">{votes} · {percent}%</span></div><div className="mt-1 h-2 overflow-hidden rounded-full bg-slate-100 dark:bg-slate-800"><div className="h-full rounded-full bg-linear-to-r from-orange-500 to-rose-500" style={{ width: `${percent}%` }}/></div>{option.votes.length > 0 && <p className="mt-1 text-xs text-slate-500">{option.votes.map((vote) => vote.profile.name || `@${vote.profile.username || "VIBE"}`).join(", ")}</p>}</div> })}</div></article>;
    })}</div>
  </section>;
}
