"use client";

import { Send, Share2, X } from "lucide-react";
import { useEffect, useState, useTransition } from "react";
import { sharePostToConversation, sharePostToStory } from "@/actions";

type Target = { id: string; label: string };

export default function SharePostButton({ postId, de }: { postId: string; de: boolean }) {
  const [open, setOpen] = useState(false); const [targets, setTargets] = useState<Target[]>([]); const [targetId, setTargetId] = useState(""); const [error, setError] = useState(""); const [pending, start] = useTransition();
  useEffect(() => { if (!open || targets.length) return; void fetch("/api/share/conversations").then((response) => response.ok ? response.json() : { conversations: [] }).then((data) => setTargets(data.conversations || [])).catch(() => setError(de ? "Chats konnten nicht geladen werden." : "Chats could not be loaded.")); }, [open, targets.length, de]);
  function share(target: "story" | "message") { start(() => { void (async () => { try { setError(""); const data = new FormData(); data.set("postId", postId); if (target === "story") await sharePostToStory(data); else { data.set("conversationId", targetId); await sharePostToConversation(data); } setOpen(false); } catch (cause) { const message = cause instanceof Error ? cause.message : ""; setError(message || (de ? "Teilen war nicht möglich." : "Sharing was not possible.")); } })(); }); }
  return <><button type="button" onClick={() => setOpen(true)} className="inline-flex items-center gap-2 rounded-full px-3 py-1.5 text-sm text-slate-600 transition hover:bg-black/5 hover:text-orange-600 dark:text-slate-300 dark:hover:bg-white/10 dark:hover:text-orange-300" aria-label={de ? "Beitrag teilen" : "Share post"}><Share2 className="size-5"/><span className="hidden sm:inline">{de ? "Teilen" : "Share"}</span></button>{open && <div className="fixed inset-0 z-[110] grid place-items-center bg-slate-950/70 p-4"><section className="w-full max-w-sm rounded-3xl bg-white p-5 shadow-2xl dark:bg-slate-900"><div className="flex items-center justify-between"><h2 className="text-lg font-black text-slate-900 dark:text-white">{de ? "Beitrag teilen" : "Share post"}</h2><button type="button" onClick={() => setOpen(false)} aria-label={de ? "Schließen" : "Close"}><X/></button></div><button type="button" disabled={pending} onClick={() => share("story")} className="mt-5 flex w-full items-center gap-3 rounded-2xl border border-orange-300 px-4 py-3 text-left font-bold text-orange-700 dark:border-orange-500/40 dark:text-orange-200"><Share2 size={19}/><span>{de ? "In deiner Story teilen" : "Share to your story"}</span></button><div className="mt-4 border-t border-slate-200 pt-4 dark:border-slate-700"><label className="text-sm font-bold text-slate-900 dark:text-white" htmlFor={`share-${postId}`}>{de ? "In Nachricht senden" : "Send in a message"}</label><select id={`share-${postId}`} value={targetId} onChange={(event) => setTargetId(event.target.value)} className="mt-2 w-full rounded-xl border border-slate-300 bg-white px-3 py-2 text-sm text-slate-900 dark:border-slate-600 dark:bg-slate-950 dark:text-white"><option value="">{de ? "Chat auswählen" : "Select a chat"}</option>{targets.map((target) => <option key={target.id} value={target.id}>{target.label}</option>)}</select><button type="button" disabled={!targetId || pending} onClick={() => share("message")} className="mt-3 inline-flex items-center gap-2 rounded-xl bg-linear-to-r from-(--ig-orange) to-(--ig-red) px-4 py-2.5 text-sm font-bold text-white disabled:opacity-50"><Send size={16}/>{de ? "Senden" : "Send"}</button></div>{error && <p className="mt-3 text-sm font-semibold text-red-600">{error}</p>}</section></div>}</>;
}
